steps:
- name: 'busybox'
  args: ['sleep', '10']
options:
  workerPool: 'projects/git-proxy-integration-test/locations/us-central1/workerPools/swp-test-pool'
gitConfig:
  http:
    proxySecretVersionName: 'projects/85159269136/secrets/swp-test-secret/latest'
source:
  gitSource:
    url: 'https://github.com/elweb9858/golang-sample'
    revision: 'main'
