steps:
- name: 'busybox'
  args: ['sleep', '10']
options:
  workerPool: 'projects/git-proxy-integration-test/locations/us-central1/workerPools/ssl-test-pool'
gitConfig:
  http:
    proxySecretVersionName: 'projects/85159269136/secrets/ssl-test/versions/latest'
    proxySslCaInfo:
      bucket: ssl-test-bucket
      object: bump.crt
      generation: 1716481921694457
source:
  gitSource:
    url: 'https://github.com/elweb9858/golang-sample'
    revision: 'main'
